### ISSUE TITLE
lib version doesn't use lib of react-icons-base

### ISSUE THREAD

**Issue by tpinne** [gorangajic/react-icons#56]
I'm using as documented `import FaBeear from 'react-icons/lib/fa/beer';` and getting the following error:

```
ERROR in ./~/react-icon-base/index.js
Module parse failed: /Users/tobias.pinnekamp/Sites/react-boilerplate/node_modules/react-icon-base/index.js Unexpected token (3:50)
You may need an appropriate loader to handle this file type.
| import { default as React, PropTypes } from 'react'
| 
| const IconBase = ({ children, color, size, style, ...props }, { reactIconBase = {} }) => {
|   const computedSize = size || reactIconBase.size || '1em'
|   return (
 @ ./~/react-icons/lib/fa/beer.js 18:15-41
 @ ./app/containers/LoginForm/index.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi main
```

the problem seems to be that the lib version of react-icons does not use the lib version of react-icons-base. Because if I edit beer.js to use the lib version of react-icons-base it's working fine.

But also I guess it has something to do, that I'm using https://github.com/mxstbr/react-boilerplate
Because in a previous learning project using the icons worked fine.

Any hints?

**Comment by Ndpnt** [comment]
Same problem here

**Comment by gorangajic** [comment]
version ? just tested and everything is working ifne

**Comment by josephcc** [comment]
Sam problem here with react-icons 2.2.1, babel-core 6.7.2, and react 0.14.7

**Comment by Ndpnt** [comment]
I temporarily fixed it by removing the `"jsnext:main": "index.js",` from the `package.json`

**Comment by Ndpnt** [comment]
For those who use webpack (as https://github.com/mxstbr/react-boilerplate), an other way to fix it it's by changing the order in `mainFields`, like this: 
```
mainFields: [
      'browser',
      'main',
      'jsnext:main',
],
```

**Comment by bsr203** [comment]
see https://github.com/gorangajic/react-icon-base/issues/13
but no activity :-(

**Comment by bsr203** [comment]
this is solved in react-icon-base v 2.0.4. It would be great if the dep of this lib is updated, and make a release. 
cc @gorangajic @bentatum

**Comment by elwhitman** [comment]
@bsr203 @bentatum @gorangajic please update the react-icon-base to v 2.0.4, the import is not working and i can't deploy without shrinkwrapping but im using yarn now

**Comment by bentatum** [comment]
Just seeing this. I'll publish soon.

**Comment by bentatum** [comment]
This should be fixed as of v2.2.2.

**Comment by JonnyBoggon** [comment]
I am still getting the error 'Module parse failed: .../node_modules/react-icons/fa/beer.js Unexpected token (6:4) You may need an appropriate loader to handle this file type.' when using v2.2.2.

**Comment by bentatum** [comment]
Sorry to hear that. Can you show me how you're importing the icon?

**Comment by JonnyBoggon** [comment]
`import FaBeer from 'react-icons/fa/beer';`

Just having that at the top of my page returns this error in my console:

`ERROR in ./~/react-icons/fa/beer.js
Module parse failed: [site-dir]/node_modules/react-icons/fa/beer.js Unexpected token (6:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (6:4)
    at Parser.pp$4.raise ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseFunctionBody ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:2098:24)
    at Parser.pp$3.parseArrowExpression ([site-dir]/node_modules/webpack/node_modules/acorn/dist/acorn.js:2087:10)
 @ ./client/components/Main.js 39:12-42
`

**Comment by bentatum** [comment]
Ok, so it works for you using `react-icons/fa/beer` but not `react-icons/lib/fa/beer`.

**Comment by JonnyBoggon** [comment]
Sorry, I have edited my comment above. It works using libs.

**Comment by bentatum** [comment]
No worries. So, it works using `react-icons/lib/fa/beer`?

**Comment by JonnyBoggon** [comment]
That is correct. I have it set up with multiple icons using the lib folder.

Thank you for your good work!

**Comment by bentatum** [comment]
Ok, cool. Importing from the /lib/ path is actually the recommended way to import right now.

Ps. You're welcome! I use react-icons probably more than anyone!

**Comment by jawakarD** [comment]
`
ERROR in ./~/react-icon-base/lib/index.js
Module not found: Error: Cannot resolve module 'prop-types' in C:\Users\Jawahr\Desktop\Projects\my exercise\react project\node_modules\react-icon-base\lib
 @ ./~/react-icon-base/lib/index.js 13:17-38`
i dont know why i am getting this i already removed `prop-types` from `peer-dependencies` in `package.json`
